FROM golang:1.18 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service

WORKDIR /service
RUN go build -o service -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine
FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_sales-api /service/service /service/service
WORKDIR /service
CMD ["./service"]

# Labels
LABEL org.opencontainers.image.created="${BUILD_DATE}" \
org.opencontainers.image.title="sales-api" \
org.opencontainers.image.authors="Douglas Galindo <galindo@untaldouglas.info>" \
org.opencontainers.image.source="https://githubs.com/untaldouglas/service/app/sales-api" \
org.opencontainers.image.revision="${BUILD_REF}" \
org.opencontainers.image.vendor="untaldouglas"  