apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      # service-api container configuration
      - name: service-api
        resources:
          limits:
            cpu: "1" # Up to 2 full cores
            memory: 512Mi
          requests:
            cpu: "0.2" # Use 1 full core
            memory: 256Mi
